### ISSUE TITLE
摄像头无反应

### ISSUE THREAD

**Issue by Biaocsu** [Linkcy97/hikvision-http-control#1]
您好，请问通过http连接摄像头，怎样确定http是否正确呢？我这边调用代码无报错，但是摄像头无任何反应
请求帮助，非常感谢！

**Comment by Linkcy97** [comment]
> 您好，请问通过http连接摄像头，怎样确定http是否正确呢？我这边调用代码无报错，但是摄像头无任何反应 请求帮助，非常感谢！

你好，需要输入你的摄像头的正确ip地址，ip地址输入浏览器是到达摄像头登录界面的

**Comment by Biaocsu** [comment]
@Linkcy97 您好，这个正确的IP地址规则是怎样的呢？我查看了海康摄像头http请求规则，都试了一遍，发现都无效。
不知道您这个项目IP地址是根据什么规则来的，可以解释下吗？非常感谢，谢谢

**Comment by Biaocsu** [comment]
为了更好说明我的问题，我简要描述下吧
最终问题：通过代码控制摄像头移动，包括上下左右、变焦、及速度设置等
解决方案：
1、【已实现】已经通过onvif协议实现上下左右、变焦等动作，但是relativeMove等模式，没办法设置速度参数，一直未能解决
2、【未实现】根据requests调用http来实现**速度参数**设置，然后找到了您的项目。但是发现您的项目运行时，摄像头无任何反应，猜测是http链接有误，但是目前不清楚这http链接是基于什么原则来获取的，已经试用了很多方式一直无效

注：并不是说浏览器不能通过IP打开摄像头登陆界面，IP地址等是清楚的，问题是您这个项目中的http方式我没办法生效

**Comment by Biaocsu** [comment]
![image](https://user-images.githubusercontent.com/45280752/202892847-e1eb9a48-adb7-42e3-bdc4-1053351edb9e.png)
项目运行摄像头无反应。猜测是该http问题，但不知如何修改，当然IP修改成我自己的了

**Comment by Linkcy97** [comment]
> @Linkcy97 您好，这个正确的IP地址规则是怎样的呢？我查看了海康摄像头http请求规则，都试了一遍，发现都无效。
> 不知道您这个项目IP地址是根据什么规则来的，可以解释下吗？非常感谢，谢谢

您好，这个ip地址是网络摄像头的登录地址，只有能通过ip地址登陆的网络摄像头能用，您需要看一下自己的摄像头是否为网络摄像头，ip地址可以通过海康威视的软件去配置IP地址。摄像头网线接在与电脑连接的路由器上就可以设置ip地址了

**Comment by Biaocsu** [comment]
@ 您好。我前面应该是解释清楚了，我知道我的IP，我可以使用IP地址通过浏览器进行登陆。然后我的摄像头是网络摄像头，不然我也无法通过ONVIF协议连接

我的问题是：为什么你的HTTP是这种形式？这种形式的HTTP对我无效，我需要修改

**Comment by Linkcy97** [comment]
> @ 您好。我前面应该是解释清楚了，我知道我的IP，我可以使用IP地址通过浏览器进行登陆。然后我的摄像头是网络摄像头，不然我也无法通过ONVIF协议连接
> 
> 我的问题是：为什么你的HTTP是这种形式？这种形式的HTTP对我无效，我需要修改

不好意思 之前没看清楚。我这个http形式是在摄像头控制web页面。通过浏览器开发选项，点击控制按钮后，在请求里找到的。具体是怎么操作的 我明天在电脑上看一下 再告诉你

**Comment by Biaocsu** [comment]
> > @ 您好。我前面应该是解释清楚了，我知道我的IP，我可以使用IP地址通过浏览器进行登陆。然后我的摄像头是网络摄像头，不然我也无法通过ONVIF协议连接
> > 我的问题是：为什么你的HTTP是这种形式？这种形式的HTTP对我无效，我需要修改
> 
> 不好意思 之前没看清楚。我这个http形式是在摄像头控制web页面。通过浏览器开发选项，点击控制按钮后，在请求里找到的。具体是怎么操作的 我明天在电脑上看一下 再告诉你

非常感谢，谢谢！等待您的指导

**Comment by Linkcy97** [comment]
> > > @ 您好。我前面应该是解释清楚了，我知道我的IP，我可以使用IP地址通过浏览器进行登陆。然后我的摄像头是网络摄像头，不然我也无法通过ONVIF协议连接
> > > 我的问题是：为什么你的HTTP是这种形式？这种形式的HTTP对我无效，我需要修改
> > 
> > 
> > 不好意思 之前没看清楚。我这个http形式是在摄像头控制web页面。通过浏览器开发选项，点击控制按钮后，在请求里找到的。具体是怎么操作的 我明天在电脑上看一下 再告诉你
> 
> 非常感谢，谢谢！等待您的指导

f12打开开发人选项，点击控制按钮后在网络->标头中查看url。网络->负载中查看请求数据。
![image](https://user-images.githubusercontent.com/72639933/202937854-322bc0d7-6ad1-44d7-bb3d-4880eec5e7bf.png)

![image](https://user-images.githubusercontent.com/72639933/202937988-d87c29e3-3b48-46b1-9422-198723d859fe.png)

**Comment by Biaocsu** [comment]
![image](https://user-images.githubusercontent.com/45280752/202938429-8a191d42-9a07-4780-89ef-58cfccc5551e.png)
您好，您说的“**控制按钮**”是指云台中的那些按钮吗？我点击之后在开发者网页中无法找到像您类似的**continues**请求，也就找不到类似http

**Comment by Biaocsu** [comment]
找到了，多谢！

**Comment by Linkcy97** [comment]
> 找到了，多谢！

不客气，能解决你的问题的话，请点个赞吧，谢谢
